# Site settings
name: JD Maresco
title: JD Maresco
email: ""
description: "JD Maresco's blog"
baseurl: ""
url: "http://jd.mares.co"
username: jdmaresco

# Build settings
markdown: kramdown
permalinks: pretty
